Fragment#2 homework
Otus-GPB/Fragments pull request #7
Opened 2022-11-08 13:41 UTC by LanaLebedeva

Fragment#2 homework (task 1 and task2)

2022-11-26 18:04 UTC, antonkazakov requested changes
Привет. Поправь плз несколько замечаний

2022-11-26 18:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/fragments/ActivityTaskTwo.kt
> +    private fun isLand() = frameFragmentBB != null
Ну это хоть и работает в твоем случае, правильнее конечно проверять ориентацию через  
getResources().getConfiguration().orientation

2022-11-26 18:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/fragments/ActivityTaskTwo.kt
> +                supportFragmentManager.beginTransaction()
В целом этот код можно было не писать. Достаточно было бы фрагменты раскидать прямо в ХМЛ файлах по квалифаерам portrait/land

2022-11-26 18:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/fragments/ArgValue.kt
> +interface ArgValue {
Довольно странные интерфейсы. 
Просто сделай паблик константы во фрагментах

2022-11-26 18:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/fragments/FragmentBB.kt
> +            if (resources.configuration.orientation == Configuration.ORIENTATION_PORTRAIT) {
Вот этот метод можно было использовать вместо isLand :)

2022-12-01 10:01 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/fragments/ActivityTaskTwo.kt
> +    private fun isLand() = frameFragmentBB != null
ОК

2022-12-01 12:19 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/fragments/ArgValue.kt
> +interface ArgValue {
Ок

2022-12-01 12:20 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/fragments/ActivityTaskTwo.kt
> +    private fun isLand() = frameFragmentBB != null
Ок

2022-12-11 14:19 UTC, antonkazakov commented
👍

2022-12-11 14:19 UTC, closed without merging